// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "apiKey": "RU2h6FREPlzoZo2Itha28uG5toGAk78U",
   "databaseId": "1TzMYNEOzScj3DaGkCDRXk72SzDi_vpHEkT6SAGNWRF4"
}