// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "apiKey": "vRMFXZvgtiTXh2K2aAI3znHQUFwbbJkk",
   "databaseId": "1WY4ARmEPKZNXCIEWdLJPa1JjLyQVhB1UQYxFsXXprYc"
}