// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "backendUrl": "https://script.google.com/macros/s/AKfycbxaiKoJp0w1-0RFoGGFG2CA0XRrunSXjiH5FZDWGUsFSfFWcdlEH9szDIsxOXUC6YsJAw/exec",
   "apiKey": "RU2h6FREPlzoZo2Itha28uG5toGAk78U",
   "databaseId": "1TzMYNEOzScj3DaGkCDRXk72SzDi_vpHEkT6SAGNWRF4"
}